spring:
  h2:
    console:
      enabled: true # h2 console 사용
      path: /h2 # localhost:port/h2 로 접근 가능
      settings:
        trace: false # Print additional trace information
        web-allow-others: true  # 브라우저로 접근가능하게 하기
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: